apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giroteste
    service: webservice
  name: giroteste
spec:
  containers:
  - image: alpine
    name: alpine
    volumeMounts:
    - mountPath: /girodir
      name: primeiro-emptydir
    command:
      - /bin/sh
      - -c
    args:
      - |
        while true; do
          echo "Executando..." >> /girodir/logs.txt
          sleep 5
        done
    resources:
      limits:
        cpu: "0.3"
        memory: "128Mi"
      requests:
        cpu: "0.1"
        memory: "64Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: primeiro-emptydir
      emptyDir:
        sizeLimit: "64Mi"
status: {}
